= ESP8266Util library for ESP8266 Arduino =

== Utility functions for ESP8266 Module & ThingSpeak API ==

This library was developed to speed up common use cases related to ESP8266 module project implementations.
Leading to bug free, faster development.


IoT usecases need cloud access, the https://thingspeak.com/ IoT service is free easy to use option.
This library has a set of basic APIs to talk to the **ThingSpeak Services**.


Debug features in this library need initialization of the *Serial* Library before 
with `Serial.begin(115200);`. The default debug is targeted on the `UART0` of the ESP8266 module.


== Example ==

```arduino
#include <ESP8266Util.h>

const char *ssid = "..........";
const char *password = "...........";

void setup() {
  // Boot-up Wait
  delay(100);
  Serial.begin(115200);
  Serial.println();
  
  // WiFi Connection
  if(Connect(ssid,password,50))
    Serial.println(" Connected");
  else
  {
    Serial.println(" Error Unable to connect");
    while(1);
  }
}

void loop() {
  // put your main code here, to run repeatedly:

}
```


=== Dependencies ===
 *Serial* Library
 Thread Safe: No
 Extendable: Yes

 
===== Note: =====
**Debug Serial Print can be Disabled** by making 
`#define NoDebug 1` on *Line 36* of `src/ESP8266Util.cpp`.


== License ==

Released Under creative commons license 3.0: Attribution-ShareAlike CC BY-SA

